### ISSUE TITLE
Avoid cloning from URL of master branch in travis CI

### ISSUE THREAD

**Issue by fangohr** [fangohr/oommf#6]
Currently, we clone from a URL (https://github.com/fangohr/oommf.git) on github (see https://github.com/fangohr/oommf/blob/master/.travis.yml#L44) for our continuous integration.

This is not ideal, as - for example for pull requests - we are not actually testing the modified in the code request but the code at https://github.com/fangohr/oommf.git

**Comment by davidcortesortuno** [comment]
Doesn't it clone the repo with the latest commits already?

**Comment by fangohr** [comment]
No, I think we always clone from the latest master at https://github.com/fangohr/oommf.git. (See line 44 in the `.travis.yml` file.) But your pull-request is not at the master before the pull request is approved, and thus we don't actually tested the pull request code there.

**Comment by marijanbeg** [comment]
Maybe the simplest solution for this could be to break the `.travis.yml` file into `Makefile` and `Dockerfile` and follow the same pattern we have in JOOMMF repositories. I prefer avoiding long Travis files because `Dockerfile` and `Makefile` are much easier to change and test (on host) and also much better supported than `.travis.yml`.

If you agree, I can do this.

**Comment by marijanbeg** [comment]
Pull request addressing this is now merged.
